import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  headrow: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  categoryrow: {
    flexDirection: 'row',
    // alignItems: 'center',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
  },

  btnrow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: height * 0.02,
  },
  topcatImg: {
    width: width * 0.42,
    height: height * 0.17,
    resizeMode: 'stretch',
    borderRadius: 10,
    marginVertical: height * 0.02,
  },

  heading: {
    fontSize: 16,
    ...FONTS.sixHundred,
    color: COLORS.black,
    marginLeft: width * 0.035,
    marginBottom: -4,
  },
  subheading: {
    fontSize: 13,
    ...FONTS.sixHundred,
    color: COLORS.gray30,
    marginLeft: width * 0.035,
    marginBottom: height * 0.01,
  },
  listbox: {
    elevation: 4,
    backgroundColor: COLORS.white,
    paddingVertical: height * 0.008,
    paddingHorizontal: height * 0.02,
    borderRadius: 6,
    marginBottom: height * 0.01,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    marginTop: height * 0.01,
  },
  listboxtext: {
    color: COLORS.black,
    ...FONTS.fiveHundred,
    fontSize: width * 0.031,
    marginBottom: -3,
  },

  oneimg: {
    width: width * 0.94,
    height: height * 0.21,
    borderRadius: 10,
    elevation: 2,
    backgroundColor: COLORS.white,
    alignSelf: 'center',
    marginBottom: height * 0.02,
    resizeMode: 'stretch',
  },
  blueBox: {
    backgroundColor: 'rgb(0, 92, 151)',
    width: width,
    alignSelf: 'center',
    paddingVertical: height * 0.026,
    marginVertical: height * 0.02,
  },

  blueBoxText: {
    color: COLORS.white,
    ...FONTS.fiveHundred,
    fontSize: width * 0.035,
    marginBottom: -3,
    alignSelf: 'center',
  },

  question: {
    color: COLORS.gray90,
    ...FONTS.sixHundred,
    fontSize: width * 0.036,
    marginHorizontal: width * 0.04,
    marginBottom: -3,
  },
  queHeading: {
    color: COLORS.primary,
    ...FONTS.sixHundred,
    fontSize: width * 0.036,
    marginHorizontal: width * 0.04,
    marginTop: height * 0.01,
  },
  questionAns: {
    color: COLORS.black,
    ...FONTS.fourHundred,
    fontSize: width * 0.033,
    marginHorizontal: width * 0.04,
  },
  blueImgBox: {
    width: width * 0.32,
    height: height * 0.153,
    borderWidth: 3,
    borderColor: COLORS.white,
    borderRadius: 10,
    marginBottom: height * 0.02,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blueImg: {
    width: width * 0.314,
    height: height * 0.15,
    resizeMode: 'stretch',
    borderRadius: 6,
  },
  // bg img

  bgimagebox: {
    width: width * 0.4,
    height: height * 0.22,
    resizeMode: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    overflow: 'hidden',
    marginVertical: height * 0.02,
  },
  bgimageinnerbox: {
    width: width * 0.18,
    height: width * 0.18,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bgimage: {
    width: width * 0.14,
    height: width * 0.14,
    resizeMode: 'stretch',
    alignSelf: 'center',
  },
  bgimagetext: {
    color: COLORS.black,
    fontSize: width * 0.033,
    ...FONTS.sixHundred,
    marginVertical: height * 0.013,
    textAlign: 'center',
    width: width * 0.3,
    height: height * 0.05,
    alignSelf: 'center',
  },

  count: {
    fontSize: width * 0.026,
    ...FONTS.fiveHundred,
    color: COLORS.white,
    borderRadius: 20,
    // marginBottom: -1,
  },
  countbox: {
    backgroundColor: '#FF0000',
    width: width * 0.04,
    height: width * 0.04,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 2,
    top: 1,
    right: width * 0.01,
  },
  bell: {
    width: width * 0.065,
    height: height * 0.05,
    resizeMode: 'contain',
    tintColor: COLORS.white,
  },
  searchicon: {
    width: width * 0.05,
    height: height * 0.024,
    resizeMode: 'contain',
    tintColor: COLORS.white,
  },
  headerbox: {
    borderWidth: 2,
    borderColor: '#1A8DD3',
    width: width * 0.09,
    height: width * 0.09,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    marginRight: width * 0.034,
  },
  headertext: {
    ...FONTS.fiveHundred,
    fontSize: width * 0.03,
    marginBottom: -4,
    color: COLORS.white,
  },

  // ----modal ----

  modaltitle: {
    fontSize: width * 0.036,
    ...FONTS.sixHundred,
    color: COLORS.black,
  },
  modalsubtitle: {
    fontSize: width * 0.03,
    ...FONTS.fourHundred,
    color: COLORS.black,
    marginVertical: height * 0.007,
  },
  simBox: {
    borderWidth: 2,
    borderColor: COLORS.gray20,
    alignItems: 'center',
    justifyContent: 'center',
    width: width * 0.24,
    height: width * 0.24,
    borderRadius: 10,
    marginHorizontal: width * 0.02,
  },
  simicon: {
    width: width * 0.06,
    height: width * 0.06,
    resizeMode: 'contain',
    marginBottom: height * 0.01,
    tintColor: COLORS.black,
  },
  modalbox: {
    backgroundColor: COLORS.white,
    width: width * 0.94,
    paddingVertical: height * 0.025,
    paddingHorizontal: height * 0.02,
    alignSelf: 'center',
    borderRadius: 16,
  },
  cancelbtn: {
    borderWidth: 2,
    borderColor: COLORS.yellow,
    backgroundColor: COLORS.white,
    width: width * 0.4,
  },
  contiBtn: {width: width * 0.4, height: height * 0.052},
  videocustomstyle: {
    alignSelf: 'center',
    marginHorizontal: width * 0.02,
    width: width * 0.94,
    height: height * 0.24,
  },
  videoinnerbox: {
    width: width * 0.94,
    alignSelf: 'center',
    borderRadius: 10,
    overflow: 'hidden',
    marginVertical: height * 0.01,
  },
});
