import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  // mainStyle: {
  //   // : 1,
  //   // borderWidth: 1,
  //   // borderColor: '#F2F2F5',
  //   // width: width,
  //   alignSelf: 'center',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   borderRadius: 8,
  //   paddingVertical: height * 0.01,
  //   marginVertical: height * 0.01,
  // },
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconrow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginVertical: height * 0.02,
  },
  heading: {
    fontSize: width * 0.036,
    ...FONTS.sixHundred,
    color: COLORS.white,
    marginBottom: -2,
    textAlign: 'center',
  },
  bgblueBox: {
    backgroundColor: COLORS.lightblue,
    width: width,
    paddingVertical: height * 0.018,
    paddingHorizontal: height * 0.015,
    marginVertical: height * 0.012,
  },
  title: {
    fontSize: width * 0.032,
    ...FONTS.fiveHundred,
    color: COLORS.white,
    marginBottom: -4,
    width: width * 0.8,
  },
  time: {
    fontSize: width * 0.03,
    ...FONTS.fiveHundred,
    color: COLORS.gray50,
    marginBottom: -4,
  },
  boxsubtitle: {
    fontSize: width * 0.032,
    ...FONTS.fourHundred,
    color: COLORS.black,
    marginTop: height * 0.02,
    lineHeight: height * 0.022,
  },
  threeicontext: {
    fontSize: width * 0.032,
    ...FONTS.fiveHundred,
    color: COLORS.gray50,
    marginBottom: -6,
    marginRight: width * 0.06,
    marginLeft:width*.008
  },
  personbox: {
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: COLORS.white,
    marginRight: width * 0.026,
  },
  person: {
    width: width * 0.09,
    height: width * 0.09,
    resizeMode: 'stretch',
    borderRadius: 10,
  },
  hiii: {
    width: width * 0.05,
    height: width * 0.05,
    resizeMode: 'stretch',
    borderRadius: 10,
    position: 'absolute',
    left: width * 0.058,
    top: height * 0.037,
  },
  profileimg: {
    width: width * 0.08,
    height: width * 0.08,
    resizeMode: 'stretch',
    borderRadius: 10,
    marginRight: width * 0.02,
  },
  dot: {
    width: width * 0.01,
    height: width * 0.01,
    backgroundColor: COLORS.gray50,
    borderRadius: 20,
    marginRight: width * 0.02,
    marginLeft: width * 0.06,
  },
  whitebox: {
    backgroundColor: COLORS.white,
    paddingVertical: height * 0.015,
    paddingHorizontal: height * 0.02,
  },
  refinputbox: {
    backgroundColor: COLORS.lightblue,
    borderRadius: 18,
    width: width * 0.93,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderTopRightRadius: 0,
    borderColor: COLORS.gray10,
  },
  carticon: {
    width: width * 0.041,
    height: width * 0.041,
    resizeMode: 'contain',
    tintColor: COLORS.gray50,
    marginRight: width * 0.007,
  },
  input: {
    fontSize: width * 0.032,
    ...FONTS.fourHundred,
    marginBottom: -3,
    paddingLeft: width * 0.01,
    width: width * 0.8,
    color:COLORS.black
  },
  threeicon: {
    width: width * 0.044,
    height: width * 0.04,
    resizeMode: 'contain',
    tintColor: COLORS.gray30,
  },
  arrow: {
    width: width * 0.034,
    height: width * 0.034,
    resizeMode: 'contain',
    tintColor: COLORS.black,
  },
});
