import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  innercontainer: {
    backgroundColor: COLORS.white,
    width: width * 0.94,
    alignSelf: 'center',
  },
  chatimage: {
    width: width * 0.44,
    height: height * 0.2,
    resizeMode: 'stretch',
    marginVertical: height * 0.01,
    alignSelf: 'flex-end',
    borderRadius: 24,
    borderTopRightRadius: 0,
  },
  chatimageleft: {
    width: width * 0.44,
    height: height * 0.2,
    resizeMode: 'stretch',
    marginVertical: height * 0.01,
    alignSelf: 'flex-start',
    borderTopLeftRadius: 0,
    borderRadius: 24,
  },
  lefttext: {
    fontSize: width * 0.034,
    ...FONTS.fourHundred,
    color: COLORS.black,
  },
  time: {
    alignSelf: 'flex-end',
    textAlign: 'right',
    width: width * 0.2,
    fontSize: width * 0.034,
    ...FONTS.fourHundred,
    color: COLORS.black,
    // bottom: 1,
    // position: 'absolute',
    // right: width * 0.03,
    // borderWidth: 1,
  },
  leftBox: {
    borderWidth: 1,
    borderRadius: 22,
    alignSelf: 'flex-start',
    borderTopLeftRadius: 0,
    width: width * 0.8,
    borderColor: COLORS.gray10,
    paddingHorizontal: width * 0.03,
    paddingVertical: width * 0.012,
    marginTop: height * 0.01,
  },
  rightBox: {
    borderWidth: 1,
    borderRadius: 22,
    borderTopRightRadius: 0,
    width: width * 0.8,
    borderColor: 'rgba(228, 228, 228, 1)',
    paddingHorizontal: width * 0.03,
    paddingVertical: width * 0.012,
    marginTop: height * 0.01,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(241, 245, 255, 1)',
  },
  inputbox: {
    borderWidth: 1,
    width: width * 0.8,
    borderRadius: 22,
    borderColor: COLORS.gray10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * 0.02,
    marginLeft: width * 0.02,
  },
  inputtext: {
    ...FONTS.fourHundred,
    fontSize: width * 0.032,
    marginBottom: -3,
    width: width * 0.56,
    marginHorizontal: width * 0.01,
    color: COLORS.black,
  },
  smileiconbox: {
    width: width * 0.092,
    height: width * 0.09,
    borderWidth: 1,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: COLORS.primary,
  },
  smileicon: {
    width: width * 0.06,
    height: height * 0.03,
    resizeMode: 'contain',
    tintColor: COLORS.primary,
  },
  fileattach2: {
    width: width * 0.09,
    height: height * 0.045,
    resizeMode: 'contain',
    tintColor: COLORS.primary,
  },
  sendimg: {
    width: width * 0.11,
    height: width * 0.11,
    resizeMode: 'contain',
    marginHorizontal: width * 0.03,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  alliconbox: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray10,
    marginVertical: height * 0.015,
    paddingVertical: height * 0.007,
    width: width * 0.7,
    borderRadius: 12,
    justifyContent: 'space-between',
    paddingHorizontal: width * 0.026,
  },
});
