import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.93,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  cartrow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heading: {
    fontSize: width * 0.038,
    ...FONTS.sixHundred,
    color: COLORS.black,
    width: width * 0.5,
    marginBottom: -3,
  },
  subtext: {
    fontSize: width * 0.032,
    ...FONTS.fourHundred,
    color: COLORS.black,
    marginVertical: height * 0.008,
    width: width * 0.5,
  },
  community: {
    width: width * 0.4,
    height: height * 0.16,
    resizeMode: 'stretch',
  },
  sixtext: {
    fontSize: width * 0.034,
    ...FONTS.sixHundred,
    color: COLORS.black,
    marginTop: height * 0.005,
  },
  sixIcon: {
    width: width * 0.048,
    height: height * 0.026,
    resizeMode: 'contain',
    tintColor: COLORS.primary,
  },
  sixbox: {
    backgroundColor: COLORS.lightblue,
    width: width * 0.29,
    marginTop: height * 0.01,
    alignItems: 'center',
    justifyContent: 'center',
    height: height * 0.09,
  },
  oneimg: {
    width: width * 0.93,
    height: height * 0.22,
    resizeMode: 'stretch',
    alignSelf: 'center',
    borderRadius: 10,
    marginVertical: height * 0.022,
  },
  cartBox: {
    backgroundColor: COLORS.lightblue,
    width: width,
    paddingVertical: height * 0.015,
    paddingHorizontal: height * 0.015,
    marginBottom: height * 0.012,
  },
  title: {
    color: COLORS.black,
    fontSize: width * 0.038,
    ...FONTS.sixHundred,
    marginBottom: -3,
  },
  subtitle: {
    fontSize: width * 0.03,
    ...FONTS.fiveHundred,
    color: COLORS.gray40,
    width: width * 0.68,
    marginVertical: height * 0.001,
  },
  cartimg: {
    width: width * 0.22,
    height: width * 0.22,
    resizeMode: 'stretch',
    marginRight: width * 0.03,
    borderRadius: 10,
    backgroundColor: COLORS.white,
  },

  bluename: {
    fontSize: width * 0.032,
    ...FONTS.sixHundred,
    color: COLORS.primary,
    marginBottom: -3,
  },
  time: {
    ...FONTS.fiveHundred,
    fontSize: width * 0.031,
    color: '#005C97',
    marginBottom: -3,
    borderRightWidth: 1,
    borderColor: COLORS.gray30,
    width: width * 0.22,
  },
  lesson: {
    ...FONTS.fiveHundred,
    fontSize: width * 0.031,
    color: '#C92C51',
    marginBottom: -3,
    marginLeft: width * 0.05,
  },
  smallimg: {
    width: width * 0.09,
    height: width * 0.09,
    borderRadius: 8,
    resizeMode: 'stretch',
  },
  smallimgbox: {
    width: width * 0.11,
    height: width * 0.11,
    borderRadius: 8,
    marginRight: width * 0.03,
    borderWidth: 3,
    borderColor: COLORS.white,
  },
  cartborder: {
    borderWidth: 1,
    borderColor: COLORS.gray10,
    paddingVertical: height * 0.014,
  },
  bgblueBox: {
    backgroundColor: COLORS.lightblue,
    width: width,
    paddingVertical: height * 0.013,
    paddingHorizontal: height * 0.015,
    marginTop: height * 0.01,
    flexDirection: 'row',
    alignItems: 'center',
  },
  videoimg: {
    width: width * 0.1,
    height: width * 0.1,
    resizeMode: 'contain',
  },
  arrow: {
    width: width * 0.036,
    height: width * 0.036,
    tintColor: COLORS.primary,
    resizeMode: 'contain',
  },
  videotext: {
    ...FONTS.sixHundred,
    fontSize: width * 0.033,
    color: COLORS.black,
    marginBottom: -3,
    width: width * 0.72,
    marginHorizontal: width * 0.03,
  },

  // -------------
  referimg: {
    width: width * 0.4,
    height: height * 0.13,
    resizeMode: 'stretch',
    marginRight: width * 0.04,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    overflow: 'hidden',
  },

  refertitle: {
    ...FONTS.sixHundred,
    fontSize: width * 0.035,
    color: COLORS.black,
    marginTop: height * 0.01,
  },
  referrupe: {
    ...FONTS.sixHundred,
    fontSize: width * 0.032,
    marginBottom: -3,
    color: COLORS.primary,
    marginBottom: height * 0.01,
  },
  coursetypebox: {
    borderWidth: 1,
    borderColor: COLORS.gray10,
    borderRadius: 12,
    flexDirection: 'row',
    marginVertical: height * 0.018,
    width: width * 0.93,
    alignSelf: 'center',
  },
});
